### ISSUE TITLE
GitLab container registry support

### ISSUE THREAD

**Issue by spijet** [texano00/urunner#10]
Hello @texano00!

I'm trying to use `urunner` to auto-restart a pod that uses an image hosted in GitLab Container registry, and it seems that the `harbor`/DockerV2 API doesn't work for those — I get "ERROR:root:Error status code: 401" in `urunner` logs. Can you please look into implementing support for GitLab registries as well?

**Comment by texano00** [comment]
Hi @spijet !
GitLab repo will be supported soon..

I'd say by the end of January.

**Comment by spijet** [comment]
Thank you! ❤️

**Comment by spijet** [comment]
Wow, that was quick! :D
Thank you for your time. Will it be possible to use this new feature for self-hosted GitLab instances as well?
