### ISSUE TITLE
Add support for arm64

### ISSUE THREAD

**Issue by RaymiiOrg** [texano00/urunner#14]
I was unable to run `urunner` on my all ARM64 cluster (https://raymii.org/s/tutorials/My_First_Kubernetes_k3s_cluster_on_3_Orange_Pi_Zero_3s_including_k8s_dashboard_hello-node_and_failover.html)

Here is a recent pull request from canary checker that added arm64 support as an example: https://github.com/flanksource/canary-checker/pull/1956/files#diff-2e71f9191e45345b53b343fdd7b8e2622685599e60237e81e8f0859a8cc03fc7

When adding an x86 node and forcing Helm to use that node, urunner works just fine:

    helm upgrade --install urunner oci://ghcr.io/texano00/urunner/helm/urunner --version 0.1.0 --values values.yaml -n urunner  --set nodeSelector."kubernetes\.io/arch"=amd64

**Comment by texano00** [comment]
@RaymiiOrg starting from
appVersion 0.5.1
helmChart 0.6.0

The following OCI platforms are supported
![image](https://github.com/user-attachments/assets/4f0d05e9-1985-4d14-9a7f-027ae79aebd2)

**Comment by RaymiiOrg** [comment]
Thank you!
